### PR TITLE
Notion Title Search & working with Notion Desktop

### PR DESCRIPTION
**Pull request by johnathanz**
* Added title search - use "nt"
* Works with Notion Desktop instead of Notion web
* Cosmetic changes in search results

### CODE REVIEW

**Comment by johnathanz** [comment]
@wrjlewis  I did run into an issue with trying to open a "New Window" for every Text / Title Search - so Search Results don't take over whatever Notion Note the user is working on (because "Back" doesn't work)

Tried this:
1) with AppleScript direct - fails because Alfred adds trailing white space??
```on run argv
  set theQuery to item 1 of argv

    tell application "System Events" to tell process "Notion"
        click menu item "New Window" of menu 1 of menu bar item "File" of menu bar 1
    end tell


  return theQuery
end run
```
image



2) So tried a Python Run Script (which opens 2 New Windows 🤯)
```
import sys
from subprocess import Popen, PIPE

query = sys.argv[1]

script = '''
    # activate application "Notion"
    tell application "System Events" to tell process "Notion"
        click menu item "New Window" of menu 1 of menu bar item "File" of menu bar 1
    end tell'''

p = Popen('osascript', stdin=PIPE, stdout=PIPE, stderr=PIPE)
p.communicate(script)

sys.stdout.write(query)

```

Any idea what the issue is Will?

**Review by wrjlewis — CHANGES_REQUESTED** [review]
Thanks for your changes, I have some comments below. 

Re: working with desktop
- This change removes support for opening notion in a web browser and instead only supports the native app. This workflow no longer works for me as someone who only uses the web app. I think this should be controlled by an env variable so users have the choice. 

Re: increase results from notion to 20
- This will slow down the results slightly, and unnecessarily given Alfred can only display max 9 items. 9, therefore, should be the limit IMO. 

Re: the changes to the subtitle
- I'm not sure I'd consider this more useful - doesn't this change simply mean the text and subtitle are always the same, therefore the subtitle never provides any additional value? Previously, you could see the parent path in the subtitle.

Re: the separation of ns and no keywords to indicate where you want to search navigable pages or not
- Looks like you haven't implemented icons in the 'nt' search, which means you can't see the emojis in the results

**Comment by wrjlewis** [comment]
Hmmm I'm unsure what is causing your issue with the app not opening a new window when you are referred by Alfred. This isn't an issue with the webapp.

I wouldn't have thought this is an issue with the trailing whitespace, probably something to do with the internal logic in the notion app itself. Do you have other instances where the app is able to open a new window from a link that isn't from alfred but outside the notion app?

**Comment by wrjlewis** [comment]
I'm making some changes to the repo and code to move everything into a python script which will allow for easier diffs and version control. I'm going to add some of the changes I mentioned above.

**Comment by johnathanz** [comment]
Hi Will, thanks for taking the time to correct my changes.

I learnt a few things 😛 

I think the way you've got the Workflow now is really good 👏

**Comment by wrjlewis** [comment]
Thanks Johnathan!

**Pull request closed without merging**
