### PR TITLE
Update to Alfred 5 User Configuration

### PR DESCRIPTION
**Pull request by vitorgalvao**
Updated to use Alfred 5’s User Configuration. This simplifies setup for users, and the code.

image

Also updated the README accordingly, and bumped the version to `0.5.0`.

Note this breaks compatibility with Alfred 4 and replaces Workflow Environment Variables. Alfred 5 recognises the `.alfred5workflow` extension, while Alfred 4 does not, which can be a simple way to separate Workflows if you which to support multiple versions at once.

[Packaged Workflow for download.](https://github.com/wrjlewis/notion-search-alfred-workflow/files/9142708/Notion.Search.alfredworkflow.zip)

### CODE REVIEW

**Comment by wrjlewis** [comment]
Hey @vitorgalvao ! 

Thanks very much for adding Alfred5 config support and updating the readme. It looks way cleaner with Alfred5 and will be easier for folk to use. 

I'm keen on still supporting Alfred4 and Alfred5 compatible versions, while people gradually migrate over time. Do you have any advice on what would be the best way to manage this within GitHub, considering the workflow uses the handy OneUpdater?

**Comment by vitorgalvao** [comment]
Check [version 2022.2 of Alias Homebrew Apps](https://github.com/alfredapp/alias-homebrew-apps-workflow/releases/tag/2022.2), specifically the coloured objects at the end. It detects the current major Alfred version and branches to each update path separately. You can set up something different on the v4 leg, or leave it empty to ensure users won’t be updated to an incompatible version. That requires releasing the intermediate version first, waiting a few days for people to update to it, then releasing the new one.

**Comment by vitorgalvao** [comment]
@wrjlewis File conflicts were introduced since the PR, so pinging to check if you’re interested in the change. This is a good workflow to include in the upcoming Alfred Gallery ([blog](https://www.alfredapp.com/blog/announcements/alfred-gallery-submit-your-favourite-workflows/); [forum](https://www.alfredforum.com/topic/19058-submitting-workflows-for-the-alfred-gallery/)).

**Comment by wrjlewis** [comment]
Hey

Thanks for the follow up. Yep still interested and aiming to spend some
time over the next weekend or two to figure how best to proceed with
Alfred5. I have a couple of updates, which involve adding an additional env
variable, that I’d like to release around the same time.

Thanks for the blog link, would be great to be on the gallery! I’ll
certainly look to submit.

**Comment by wrjlewis** [comment]
Merged here https://github.com/wrjlewis/notion-search-alfred5-workflow/pull/2/commits/93e95a1b877d5c9a033da7c4bdaa48ada9efb178

I set up a new repo to support Alfred5 and I will maintain both for now. 

Thanks @vitorgalvao, I'll submit to the gallery too shortly.

**Pull request closed without merging**
